# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qroundprogressbar import QRoundProgressBar



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setObjectName("Form")
        Form.resize(794, 483)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 52, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 52, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 52, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 52, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 791, 71))
        self.frame.setStyleSheet("background-color: rgb(163, 73, 164);\n"
"border: 5px solid black;\n"
"border-top:0px;\n"
"border-radius:5px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(300, 10, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("border: 5px solid black;\n"
"border-bottom: 0px;\n"
"border-radius: 10px;")
        self.title.setObjectName("title")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(20, 0, 81, 61))
        self.logo.setStyleSheet("border: 5px solid black;\n"
"border-top: 0px;\n"
"border-radius: 10px;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("logo.ico"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(660, 0, 121, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(163, 73, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 73, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 73, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 73, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 73, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 73, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 73, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 73, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 73, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_3.setPalette(palette)
        self.label_3.setStyleSheet("border: 5px solid black;\n"
"border-top: 0px;\n"
"border-radius: 10px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.close = QtWidgets.QPushButton(self.frame)
        self.close.setGeometry(QtCore.QRect(730, 10, 40, 40))
        self.close.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.close.setFont(font)
        self.close.setStyleSheet("QPushButton#close {\n"
"                background-color: transparent;\n"
"                color: rgb(166, 0, 0);\n"
"                border: 5px solid rgb(166, 0, 0);\n"
"                border-radius: 5px\n"
"                }\n"
"\n"
"QPushButton#close::hover {\n"
"                background-color: red;\n"
"        }")
        self.close.setObjectName("close")
        self.minimize = QtWidgets.QPushButton(self.frame)
        self.minimize.setGeometry(QtCore.QRect(680, 10, 40, 40))
        self.minimize.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(19)
        self.minimize.setFont(font)
        self.minimize.setStyleSheet("QPushButton#minimize {\n"
"                background-color: transparent;\n"
"                color: rgb(52, 107, 1);\n"
"                border: 5px solid rgb(52, 107, 1);\n"
"                border-radius: 5px}\n"
"\n"
"QPushButton#minimize::hover {\n"
"                        background-color: green\n"
"                }\n"
"")
        self.minimize.setObjectName("minimize")
        self.counter_tab = QtWidgets.QTabWidget(Form)
        self.counter_tab.setGeometry(QtCore.QRect(10, 70, 781, 411))
        self.counter_tab.setStyleSheet("QTabBar::tab{\n"
"        background-color: rgb(163, 73, 164);\n"
"        border: 4px solid black;\n"
"        border-right: 0px;    \n"
"        border-radius: 10px;\n"
"        margin-top: 10px;\n"
"        margin-bottom: 5px;\n"
"        padding: 5px;\n"
"        padding-right: -8px\n"
"    }\n"
"\n"
"    QTabBar::tab:selected  {\n"
"        background-color: rgb(118, 52, 118);\n"
"        color: gray;\n"
"        border-color: black;\n"
"    }\n"
"\n"
"QTabWidget>QWidget>QWidget{\n"
"        background-color: rgb(118, 52, 118);\n"
"        border: 5px solid black; border-left:0px; border-top: 0\n"
"    }")
        self.counter_tab.setTabPosition(QtWidgets.QTabWidget.West)
        self.counter_tab.setIconSize(QtCore.QSize(125, 95))
        self.counter_tab.setObjectName("counter_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.progressBar =QRoundProgressBar(self.tab)
        self.progressBar.visible = True
        self.progressBar.setFormat('25:00')
        font = QtGui.QFont()
        font.setPointSize(17)
        self.progressBar.setFont(font)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.resize(250, 150)
        self.progressBar.move(250, 130)


        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(240, 320, 191, 61))

        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background: transparent;\n"
"border: 5px solid black;\n"
"border-radius: 10px;\n"
"color:white\n"
"")
        self.pushButton.setObjectName("start")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 50, 661, 61))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.task = QtWidgets.QComboBox(self.widget)
        self.task.setMinimumSize(QtCore.QSize(550, 40))
        self.task.setMaximumSize(QtCore.QSize(550, 30))
        self.task.setStyleSheet("background:white;\n"
"border: 5px solid black;\n"
"border-radius: 5px;\n"
"font-size: 20px;")
        self.task.setEditable(True)
        self.task.setObjectName("task")
        self.horizontalLayout.addWidget(self.task)
        self.status = QtWidgets.QPushButton(self.widget)
        self.status.setMinimumSize(QtCore.QSize(60, 30))
        self.status.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.status.setFont(font)
        self.status.setStyleSheet("QPushButton#status {\n"
"    background-color: red;\n"
"    font-size: 16px;\n"
"    border: 2px solid white;\n"
"    border-radius: 10px;\n"
"    }\n"
"\n"
"QPushButton#status::hover {\n"
"     background-color: green;\n"
"    }")
        self.status.setObjectName("status")
        self.horizontalLayout.addWidget(self.status)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("counter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.counter_tab.addTab(self.tab, icon, "")
        self.tasks_tab = QtWidgets.QWidget()
        self.tasks_tab.setObjectName("tasks_tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tasks_tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 671, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.setColumnWidth(0, 300)
        self.tableWidget.setColumnWidth(1, 80)
        self.tableWidget.setColumnWidth(2, 150)
        self.tableWidget.setColumnWidth(3, 100)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("tasks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.counter_tab.addTab(self.tasks_tab, icon1, "")

        self.retranslateUi(Form)
        self.counter_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "POMODORO"))
        self.close.setText(_translate("Form", "X"))
        self.close.setShortcut(_translate("Form", "Ctrl+W"))
        self.minimize.setText(_translate("Form", "_"))
        self.pushButton.setText(_translate("Form", "START"))
        self.status.setText(_translate("Form", "Done"))
        self.status.setShortcut(_translate("Form", "Ctrl+D"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Tasks"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Status"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Expiry Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Duration Taken"))
